FROM golang:1.18 as builder

RUN apt-get update && apt-get install -y \
    && apt-get clean

WORKDIR /app

COPY go.mod go.sum /app/
RUN go mod download

COPY . /app/

RUN CGO_ENABLED=0 GOOS=linux go build -a -o api_main ./app/api

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/api_main .

# Optionally expose a default port
EXPOSE 8080

CMD ["./api_main"]